language: csharp
mono: none
dotnet: 3.1.102
solution: DiLite.sln
script:
  # Restore and build
  - dotnet tool restore
  - dotnet restore
  - dotnet build

  # MINICOVER: instrument
  - dotnet minicover instrument --workdir ./ --assemblies /**/bin/**/*.dll --sources ./DiLite/**/*.cs

  # MINICOVER: reset hits
  - dotnet minicover reset

  # Run the tests
  - dotnet test --no-build

  # MINICOVER: uninstrument
  - dotnet minicover uninstrument

  # MINICOVER: create coveralls report
  - dotnet minicover report --threshold 5
  - dotnet minicover coverallsreport --root-path ./ --workdir ./ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"