name: Build Branch

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Install tools
      run: dotnet tool restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Instrument Minicover
      run: dotnet minicover instrument --workdir ./ --assemblies /**/bin/**/*.dll --sources /DiLite/**/*.cs
    - name: Reset Minicover hits
      run: dotnet minicover reset
    - name: Test
      run: dotnet test --no-build --settings coverlet.runsettings
    - name: Uninstrument Minicover
      run: dotnet minicover uninstrument
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: "!**/.nuget/packages/**/*.*"
        flags: ${{ runner.os }},netcore${{ matrix.dotnet }}
