name: Build Branch

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Debug Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: ["3.1"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2.1.2
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core ${{ matrix.dotnet }} SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --settings coverlet.runsettings

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: "!**/.nuget/packages/**/*.*"
        flags: ${{ runner.os }},netcore${{ matrix.dotnet }}
